// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// ws2813b //
// ------- //

#define ws2813b_wrap_target 0
#define ws2813b_wrap 3
#define ws2813b_pio_version 0

static const uint16_t ws2813b_program_instructions[] = {
            //     .wrap_target
    0x6021, //  0: out    x, 1                       
    0xe601, //  1: set    pins, 1                [6] 
    0xa201, //  2: mov    pins, x                [2] 
    0xe900, //  3: set    pins, 0                [9] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ws2813b_program = {
    .instructions = ws2813b_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = 0,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ws2813b_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ws2813b_wrap_target, offset + ws2813b_wrap);
    return c;
}
#endif

